[build]
  command = "pnpm build"       
  publish = "dist"            

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  
[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "br"
